### ISSUE TITLE
Document.reference date is an instant and should not provide an error when translating

### ISSUE THREAD

**Issue by oliveregger** [i4mi/MobileAccessGateway#76]
1. caused by: org.openehealth.ipf.commons.ihe.xds.core.validate.XDSMetaDataException: Invalid time format: 202205121104360400
at org.openehealth.ipf.commons.ihe.xds.core.metadata.Timestamp.fromHL7(Timestamp.java:126) ~[ipf-commons-ihe-xds-4.2.0.jar!/:4.2.0]
at ch.bfh.ti.i4mi.mag.mhd.iti65.Iti65RequestConverter.timestampFromDate(Iti65RequestConverter.java:298) ~[classes!/:na

[ProvideBundle_MAGMED005.txt](https://github.com/i4mi/MobileAccessGateway/files/8680794/ProvideBundle_MAGMED005.txt)
]

2. follow up error message: The patient ID in the document entry does not match the client auth

**Comment by oliveregger** [comment]
1. Issue was that timezone with minus signal the minus is stripped
2. The patient ID in document entry does not match the client auth -> the MPI-PID in List.subject could not be resolved, pmp has the format for the absolute url with:  https://test.ahdis.ch/mag-pmp/fhir/Patient/2.16.756.5.30.1.191.1.0.2.1-7a4ec59f-a024-4cfb-bc04-3339c53cb9ac
